### ISSUE TITLE
Update tsl550 laser to inherit from Instrument, implement abstract functions.

### ISSUE THREAD

**Issue by sequoiap** [BYUCamachoLab/pyrolab#15]
The TSL550 class needs to inherit from Instrument in order to be compatible with PyroLab's instrument server.

A few notes:
- [x] Make sure that `close()` releases the serial port connection, if necessary--try looking into pyserial docs to see if that needs to be done.
- [x] `detect_devices()` should return a list--can we sweep through all available USB ports to find if the device is detected? Perhaps by comparing the return value from an IDENT function to a known substring (like "Santec TSL550" or the likes)

**Comment by BenA8** [comment]
I checked the close() function, and it looks like it does release the serial port connection. I came across several questions, though, as I was working with some of the other parts of the class.
The __init__ had a parameter 'address,' but it doesn't have a default value, and I'm assuming we'll want it to have one. It's the first argument passed for the serial.Serial function, which I think means it's the port. Should it's default value be some port then, or is it just the name of the device, or should it be just None?
I was also wondering what the dictionary is that detect_devices() returns? And what should be the string and the AnyType for each pair?

**Comment by sequoiap** [comment]
Yes, we'll want `__init__()` to have a default value. It's the address, which on our computer is "COM4". But, that's just because of which port it's plugged into in the back, and is a bad default value. Two options; we could make it something like "COM1" to give an example of what its form usually is, but I also really like the idea of making it None and just mentioning what typical values might be in the docstring for that argument. Be sure to typehint it as a string. In that case, you can either make the default the empty string (i.e. "") else the typehint will need to be `Union[str, None]` for the linter to not complain.

`detect_devices()` returns a dictionary of string-value pairs that match the arguments of `connect()`. In the case of this laser, the return value would look something like (spaced nicely for reading):

```
[
    {
        "address": "COM4',
        "baudrate": 9600,
        "terminator": "\r",
        "timeout": 100,
        "query_delay": 0.05,
    },
    ...
]
```
