### ISSUE TITLE
Update Kinesis instruments

### ISSUE THREAD

**Issue by sequoiap** [BYUCamachoLab/pyrolab#19]
The Kinesis instruments each need:

- [x] Documentation on how to install the required DLL's from ThorLabs' website
- [x] Needs to implement the functions (`connect()`, `detect_devices()` (can return an empty list), `close()`) defined by `class Instrument`

**Comment by edgedancerofUrithiru** [comment]
So if I am understanding this correctly KinesisInstrument inherits from Instrument and the 3 stages should inherit from KinesisInstrument?

**Comment by edgedancerofUrithiru** [comment]
Also, I am realizing that I do not know how to implement these functions, how do you connect to the thorlabs devices?

**Comment by sequoiap** [comment]
Correct, KinesisInstrument inherits from Instrument, the stages inherit from KinesisInstrument.
